service: home-auto

provider:

  name: aws

  runtime: nodejs10.x

  region: eu-west-1

functions:

  shortbot:

    handler: handler.homeauto

    events:

      - http:

          path: home-auto

          method: post

          cors: true
